bounds:
  x: [0, 50] # x-bounds
  y: [0, 50] # y-bounds
  z: [0, 50] # z-bounds
  
initial_configuration: [[1, 1, 1], [3, 1, 1],[7, 6, 4], [1, 2, 5], [3, 9, 15], [2, 44, 9], [1, 9, 5],[25, 19, 11], [18, 13, 8], [22, 3, 6], [29, 15, 29], [2, 2, 38]] # The initial configuration (3D position) of all drones

obstacles:
  - type: box
    position: [10, 10, 1] # The 3D position of the obstacle in the environment
    size: [4, 4, 2] # The side lengths of the box-shaped obstacle
    rotation: [0, 0, 0]  # Euler angles in degrees
    color: red
    
  - type: cylinder
    endpoints: [[15, 10, 0], [15, 10, 15]] # The 3D endpoints of the cylinder
    radius: 2.5 # The radius of the cylinder in meters
    rotation: [0, 0, 0]
    color: red

  - type: sphere
    position: [5, 10, 2]
    radius: 2.0 # The radius of the sphere in meters
    color: red

  - type: box
    position: [18, 10, 1] # The 3D position of the obstacle in the environment
    size: [4, 4, 2] # The side lengths of the box-shaped obstacle
    rotation: [0, 0, 0]  # Euler angles in degrees
    color: red

  - type: sphere
    position: [35, 20, 2]
    radius: 2.5
    color: red

goals:
  - position: [ 30, 30, 2 ] # The 3D position of the first goal
    radius: 1.0 # The radius of the first goal
  - position: [ 20, 30, 2 ] # The 3D position of the second goal
    radius: 1.0 # The radius of the second goal
  - position: [28, 39, 27]
    radius: 1.0
  - position: [21, 24, 39]
    radius: 1.0
  - position: [21, 26, 27]
    radius: 1.0
  - position: [35, 24, 32]
    radius: 1.0
  - position: [28, 37, 23]
    radius: 1.0
  - position: [25, 19, 11]
    radius: 1.0
  - position: [18, 27, 43]
    radius: 1.0
  - position: [13, 48, 32]
    radius: 1.0
  - position: [1, 35, 26]
    radius: 1.0
  - position: [43, 32, 45]
    radius: 1.0